version: "3"
services:
  hitch-hike:
    container_name: hitch-hike
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/hitch-hike'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27015:27017