version: "3"
services:
  i-car-share:
    container_name: i-car-share
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/i-car-share'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27015:27017